apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
resources:
  - workspaces/workspace-build-pvc.yaml
  - workspaces/workspace-release-pvc.yaml
  - workspaces/workspace-m2-repo.yaml
  - resources/resource-git-petclinic.yaml
  - resources/github-secret.yaml
  - tasks/clean.yaml
  - tasks/maven.yaml
  - tasks/oc-start-s2i.yaml
  - tasks/openshift-client.yaml
  - tasks/print.yaml
  - pipelines/build-pipeline.yaml
  - pipelines/release-pipeline.yaml
  - serviceaccounts/pipeline-sa.yaml
  - triggers/build-template.yaml
  - triggers/build-binding.yaml
  - triggers/build-event-listener.yaml
  - triggers/trigger-route.yaml
  